theme: jekyll-theme-minimal
auto_dark_mode: true
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: "EC M202A Project - Lights Under Attack: Stress-Testing Noise-Coded Illumination"
description: "Course project website for EC M202A / CS M213A (Fall 2025)"
# For user pages, url should be "https://username.github.io" and baseurl: ""
# For project pages, url: "https://username.github.io" and baseurl: "/repo-name"
url: "https://MaxwellJung.github.io"
baseurl: "/ecem202a" # replace with your project name, e.g., "/ECEM202A_2025Fall_Project_1"

markdown: kramdown
kramdown:
  input: GFM

# Necessary for GitHub Pages
plugins: []